"""Report generation service.

Generates investigation analysis reports with clear distinctions between:
- Observed fact
- Algorithmic inference
- Investigator annotation
"""

import json
import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import ALGORITHM_VERSION
from app.models.case import Case
from app.models.entity import Entity, CaseEntity
from app.models.evidence import Evidence
from app.models.lead import Lead
from app.models.relationship import Relationship
from app.services.graph_service import GraphService
from app.services.lead_service import LeadService


class ReportService:
    def __init__(self, db: AsyncSession):
        self.db = db

    async def generate_case_report(self, case_id: uuid.UUID) -> dict[str, Any]:
        """Generate a comprehensive investigation analysis report for a case."""
        # Load case
        case_result = await self.db.execute(select(Case).where(Case.id == case_id))
        case = case_result.scalar_one()
        if case is None:
            raise ValueError(f"Case {case_id} not found.")

        # Get entities
        ce_stmt = (
            select(CaseEntity, Entity)
            .join(Entity, CaseEntity.entity_id == Entity.id)
            .where(CaseEntity.case_id == case_id)
        )
        ce_result = await self.db.execute(ce_stmt)
        entities = [{"case_entity": ce, "entity": e} for ce, e in ce_result.all()]

        # Get evidence
        ev_stmt = select(Evidence).where(Evidence.case_id == case_id)
        ev_result = await self.db.execute(ev_stmt)
        evidence = ev_result.scalars().all()

        # Get relationships
        rel_stmt = select(Relationship).where(Relationship.case_id == case_id)
        rel_result = await self.db.execute(rel_stmt)
        relationships = rel_result.scalars().all()

        # Get leads
        lead_stmt = select(Lead).where(Lead.case_id == case_id)
        lead_result = await self.db.execute(lead_stmt)
        leads = lead_result.scalars().all()

        # Get key entities
        graph_service = GraphService(self.db)
        key_entities = await graph_service.get_key_entities(case_id)

        # Get suspicious patterns
        patterns = await graph_service.detect_suspicious_patterns(case_id)

        # Build report
        report = {
            "report_type": "INVESTIGATION_ANALYSIS",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "algorithm_version": ALGORITHM_VERSION,
            "disclaimer": (
                "This report is generated by APEX LINK, an investigative decision-support platform. "
                "Analytical scores, graph prominence, correlations, and detected patterns are potential "
                "leads generated from available data. They do not establish criminal responsibility "
                "and must be independently reviewed by an authorized investigator."
            ),
            "case_summary": {
                "case_number": case.case_number,
                "title": case.title,
                "description": case.description,
                "category": case.category,
                "priority": case.priority.value if case.priority else "MEDIUM",
                "status": case.status.value if case.status else "OPEN",
                "location": case.location,
                "incident_date": case.incident_date.isoformat() if case.incident_date else None,
            },
            "known_entities": {
                "total": len(entities),
                "by_type": self._count_by_type(entities),
                "entities": [
                    {
                        "type": e["entity"].entity_type,
                        "value": e["entity"].display_value,
                        "confidence": e["entity"].confidence,
                        "observation_type": "OBSERVED_FACT",
                    }
                    for e in entities
                ],
            },
            "key_network_entities": {
                "total": len(key_entities),
                "entities": [
                    {
                        "label": ke["label"],
                        "type": ke["entity_type"],
                        "score": ke["score"],
                        "factors": ke["factors"],
                        "observation_type": "ALGORITHMIC_INFERENCE",
                    }
                    for ke in key_entities
                ],
            },
            "network_statistics": {
                "total_relationships": len(relationships),
                "relationship_types": self._count_rel_types(relationships),
            },
            "cross_case_correlations": {
                "leads_generated": len(leads),
                "leads": [
                    {
                        "related_case": str(l.related_case_id) if l.related_case_id else None,
                        "score": l.score,
                        "priority": l.priority.value,
                        "explanation": l.explanation,
                        "observation_type": "ALGORITHMIC_INFERENCE",
                    }
                    for l in leads
                ],
            },
            "suspicious_patterns": [
                {
                    "pattern": p["pattern"],
                    "description": p["description"],
                    "entity": p.get("label", "N/A"),
                    "observation_type": "ALGORITHMIC_INFERENCE",
                }
                for p in patterns
            ],
            "evidence_summary": {
                "total": len(evidence),
                "by_type": {e.evidence_type.value: 0 for e in evidence},
                "items": [
                    {
                        "number": e.evidence_number,
                        "type": e.evidence_type.value,
                        "filename": e.filename,
                        "integrity_hash": e.sha256_hash,
                        "observation_type": "OBSERVED_FACT",
                    }
                    for e in evidence
                ],
            },
            "limitations": [
                "Analysis is based on currently available evidence and data.",
                "Results are algorithmic inferences, not definitive conclusions.",
                "Entity extraction may have false positives and false negatives.",
                "Cross-case correlations indicate shared identifiers, not proven connections.",
                "This prototype operates on synthetic/demo data.",
            ],
        }

        # Count evidence by type
        for e in evidence:
            report["evidence_summary"]["by_type"][e.evidence_type.value] = (
                report["evidence_summary"]["by_type"].get(e.evidence_type.value, 0) + 1
            )

        return report

    def _count_by_type(self, entities: list[dict]) -> dict[str, int]:
        counts: dict[str, int] = {}
        for e in entities:
            t = e["entity"].entity_type
            counts[t] = counts.get(t, 0) + 1
        return counts

    def _count_rel_types(self, relationships: list) -> dict[str, int]:
        counts: dict[str, int] = {}
        for r in relationships:
            t = r.relationship_type.value
            counts[t] = counts.get(t, 0) + 1
        return counts
